# Generated by Django 5.2.8 on 2025-11-13 17:10

import django.db.models.deletion
import django.utils.timezone
import reservations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now, validators=[reservations.models.validate_reservation_date])),
                ('time', models.TimeField(validators=[reservations.models.validate_reservation_time])),
                ('guests', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('date', 'time', 'user')},
            },
        ),
    ]
